using AutoMapper;
using Published.Application.Response;
using Published.Core.Entities;

namespace Published.Application.Mappers
{
    public class RepoDetailsMapper : Profile
    {
        public RepoDetailsMapper()
        {
            CreateMap<RepoDetail, BatchRepoDetailsRes>()
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.Repo != null ? src.Repo.Job.UserId : 0L))
                .ForMember(dest => dest.Source, opt => opt.MapFrom(src => src.Repo != null ? src.Repo.Job.Source : null))
                .ForMember(dest => dest.RepoUrl, opt => opt.MapFrom(src => src.Repo != null ? src.Repo.RepoUrl : null))
                .ForMember(dest => dest.AutoGeneratedPost, opt => opt.MapFrom(src => src.Value))
                .ForMember(dest => dest.PostedOn, opt => opt.MapFrom(src => src.Repo != null ? src.Repo.PostedOn : src.CreatedOn));
        }
    }
}
