using System;
using System.Collections.Generic;
using Home.Core.Entities;
using Microsoft.EntityFrameworkCore;

namespace Home.Core.Persistence;

public partial class HomeDbContext : DbContext
{
    public HomeDbContext()
    {
    }

    public HomeDbContext(DbContextOptions<HomeDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BatchJobStatus> BatchJobStatuses { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BatchJobStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK_SyncJob");

            entity.ToTable("BatchJobStatus", "Home");

            entity.Property(e => e.Status)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_User.Posts");

            entity.ToTable("Posts", "Home");

            entity.Property(e => e.Author).HasMaxLength(100);
            entity.Property(e => e.AutoGeneratedPostByAi).HasColumnName("AutoGeneratedPostByAI");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.PostedOn).HasColumnType("datetime");
            entity.Property(e => e.RepoUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Source)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Title).HasMaxLength(100);
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
