using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace Published.Application.Response
{
    public record BatchRepoRes
    {
        public long UserId { get; init; }

        public string? AutoGeneratedPost { get; init; }

        public string? AutoGeneratedPostByAI { get; init; }

        public string? Source { get; init; } 

        public string? RepoUrl { get; init; }

        public DateTime PostedOn { get; init; }

    }
}
