using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace Published.Application.Response
{
    public record BatchRepoRes
    {
        public long ProcessedPostId { get; set; }

        public long UserId { get; set; }

        public string? Author { get; set; }

        public string? Title { get; set; }

        public string? AutoGeneratedPost { get; set; }

        public string? AutoGeneratedPostByAi { get; set; }

        public string? Source { get; set; }

        public string? RepoUrl { get; set; }

        public DateTime PostedOn { get; set; }

    }
}
