
    CREATE TABLE [Published].[ProcessedPosts] (
    [ProcessedPostId]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [RepoId]               BIGINT         NOT NULL,
    [Headline]             NVARCHAR (500) NULL,
    [OriginalTitle]        NVARCHAR (500) NULL,
    [OriginalAuthor]       NVARCHAR (500) NULL,
    [Summary]              NVARCHAR (MAX) NULL,
    [Takeaways]            NVARCHAR (MAX) NULL,
    [CTA]                  NVARCHAR (MAX) NULL,
    [Hashtags]             NVARCHAR (500) NULL,
    [OriginalBaseUrl]      NVARCHAR (500) NULL,
    [AutoGeneratedPost]    NVARCHAR (MAX) NULL,
    [AutoGeneratedPostByAI] NVARCHAR (MAX) NULL,
    [IsActive]             BIT            NOT NULL,
    [CreatedOn]            DATETIME       NOT NULL,
    [CreatedBy]            BIGINT         NOT NULL,
    [UpdatedOn]            DATETIME       NULL,
    [UpdatedBy]            BIGINT         NULL,
    CONSTRAINT [PK_Published.ProcessedPosts] PRIMARY KEY CLUSTERED ([ProcessedPostId] ASC),
    CONSTRAINT [FK_ProcessedPosts_Repos] FOREIGN KEY ([RepoId]) REFERENCES [Published].[Repos] ([RepoId])
);
GO

-- Create indexes for performance optimization
CREATE INDEX [IX_ProcessedPosts_RepoId] ON [Published].[ProcessedPosts] ([RepoId]);
GO
CREATE INDEX [IX_ProcessedPosts_Id_Active] ON [Published].[ProcessedPosts] ([ProcessedPostId], [IsActive]);
GO
