using System;
using System.Collections.Generic;

namespace Home.Core.Entities;

public partial class Post
{
    public long Id { get; set; }

    public long ProcessedPostId { get; set; }

    public long UserId { get; set; }

    public string? Author { get; set; }

    public string? Title { get; set; }

    public string? AutoGeneratedPost { get; set; }

    public string? AutoGeneratedPostByAi { get; set; }

    public string? Source { get; set; }

    public string? RepoUrl { get; set; }

    public bool IsActive { get; set; }

    public DateTime PostedOn { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public long? UpdatedBy { get; set; }
}
