using MediatR;
using Microsoft.EntityFrameworkCore;
using PostIQ.Core.Response;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Home.Application.Commands
{
    /// <summary>
    /// Command to upsert a batch of posts.
    /// Models is an init-only collection and defaults to empty to avoid null checks.
    /// </summary>
    public class MergePostCommand : IRequest<SingleResponse<bool>>
    {
        public List<MergePostModel> Models { get; set; }
    }

    public class MergePostModel
    {
        public long ProcessedPostId { get; set; }

        public long UserId { get; set; }

        public string? Author { get; set; }

        public string? Title { get; set; }

        public string? AutoGeneratedPost { get; set; }

        public string? AutoGeneratedPostByAi { get; set; }

        public string? Source { get; set; }

        public string? RepoUrl { get; set; }

        public DateTime PostedOn { get; set; }
    }
}
