using AutoMapper;
using MediatR;
using Microsoft.EntityFrameworkCore;
using PostIQ.Core.Database;
using PostIQ.Core.Response;
using Published.Application.Queries;
using Published.Application.Response;
using Published.Application.Services;
using Published.Core.Entities;
using Published.Core.Persistence;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Published.Application.Handlers
{
    public class GetBatchReposHandler : IRequestHandler<GetBatchReposQuery, ListResponse<BatchRepoRes>>
    {
        private readonly IRepositoryAsync<ProcessedPost> _processedPosts;
        private readonly IMapper _mapper;

        public GetBatchReposHandler(
            IUnitOfWork<PublishDbContext> uow,
            IMapper mapper)
        {
            _processedPosts = uow.GetRepositoryAsync<ProcessedPost>();
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }
        public async Task<ListResponse<BatchRepoRes>> Handle(GetBatchReposQuery request, CancellationToken cancellationToken)
        {
            var result = await _processedPosts.GetListAsync(
                predicate: x => x.ProcessedPostId > request.AfterId && x.IsActive,
                orderBy: o => o.OrderBy(x => x.ProcessedPostId),
                include: i => i.Include(p => p.Repo)
                                .ThenInclude(r => r.Job),
                index: -1, 
                size: request.BatchSize + 1,
                enableTracking: false);

            var mappedItems = result.Data.Take(request.BatchSize).Select(processedPost => new BatchRepoRes
            {
                UserId = processedPost.Repo.Job.UserId,
                Source = processedPost.Repo.Job.Source,
                RepoUrl = processedPost.Repo.RepoUrl,
                PostedOn = processedPost.Repo.PostedOn,
                AutoGeneratedPost = processedPost.AutoGeneratedPost ?? string.Empty,
                AutoGeneratedPostByAI = processedPost.AutoGeneratedPostByAI ?? string.Empty
            }).ToList();

            var hasMoreRecords = result.Data.Count > request.BatchSize;
            var lastProcessedId = result.Data.Take(request.BatchSize).Select(x => x.ProcessedPostId).OrderByDescending(id => id).FirstOrDefault();
            
            // Calculate current page number based on AfterId and BatchSize
            // Page 1 is when AfterId is 0 or not provided
            var currentPage = request.AfterId == 0 ? 1 : (int)Math.Ceiling((double)(request.AfterId + 1) / request.BatchSize);
            
            // Calculate total pages based on total count of records and batch size
            var totalPages = (int)Math.Ceiling((double)result.Count / request.BatchSize);

            var response = new ListResponse<BatchRepoRes>(mappedItems)
            {
                Size = mappedItems.Count,
                Page = currentPage,
                PerPage = request.BatchSize,
                Count = mappedItems.Count,
                TotalPages = totalPages,
                HasPrevious = request.AfterId > 0,
                HasNext = hasMoreRecords,
                LastProcessedId = lastProcessedId
            };

            return response;
        }
    }
}
