using Published.Core.Entities;

namespace Published.Application.Services
{
    public interface IProcessedPostService
    {
        Task SaveProcessedPostAsync(
            long repoId,
            string? headline,
            string? originalTitle,
            string? originalAuthor,
            string? summary,
            string? takeaways,
            string? cta,
            string? hashtags,
            string? originalBaseUrl,
            string? autoGeneratedPost,
            string? autoGeneratedPostByAI,
            long userId,
            CancellationToken cancellationToken = default);

        Task<ProcessedPost?> GetProcessedPostByRepoIdAsync(
            long repoId,
            CancellationToken cancellationToken = default);
    }
}
