using PostIQ.Core.Database;
using Published.Core.Entities;
using Published.Core.Persistence;

namespace Published.Application.Services
{
    public class ProcessedPostService : IProcessedPostService
    {
        private readonly IRepositoryAsync<ProcessedPost> _processedPostRepository;
        private readonly IRepository<ProcessedPost> _processedPostRepositorySync;
        private readonly IUnitOfWork<PublishDbContext> _uow;

        public ProcessedPostService(IUnitOfWork<PublishDbContext> uow)
        {
            _uow = uow ?? throw new ArgumentNullException(nameof(uow));
            _processedPostRepository = uow.GetRepositoryAsync<ProcessedPost>();
            _processedPostRepositorySync = uow.GetRepository<ProcessedPost>();
        }

        public async Task SaveProcessedPostAsync(
            long repoId,
            string? headline,
            string? originalTitle,
            string? originalAuthor,
            string? summary,
            string? takeaways,
            string? cta,
            string? hashtags,
            string? originalBaseUrl,
            string? autoGeneratedPost,
            string? autoGeneratedPostByAI,
            long userId,
            CancellationToken cancellationToken = default)
        {
            // Check if a processed post already exists for this repo
            var existingPost = await _processedPostRepository.SingleOrDefaultAsync(
                p => p.RepoId == repoId);

            if (existingPost != null)
            {
                // Update existing record
                existingPost.Headline = headline;
                existingPost.OriginalTitle = originalTitle;
                existingPost.OriginalAuthor = originalAuthor;
                existingPost.Summary = summary;
                existingPost.Takeaways = takeaways;
                existingPost.CTA = cta;
                existingPost.Hashtags = hashtags;
                existingPost.OriginalBaseUrl = originalBaseUrl;
                existingPost.AutoGeneratedPost = autoGeneratedPost;
                existingPost.AutoGeneratedPostByAI = autoGeneratedPostByAI;
                existingPost.UpdatedOn = DateTime.UtcNow;
                existingPost.UpdatedBy = userId;

                _processedPostRepositorySync.Update(existingPost);
            }
            else
            {
                // Insert new record
                var processedPost = new ProcessedPost
                {
                    RepoId = repoId,
                    Headline = headline,
                    OriginalTitle = originalTitle,
                    OriginalAuthor = originalAuthor,
                    Summary = summary,
                    Takeaways = takeaways,
                    CTA = cta,
                    Hashtags = hashtags,
                    OriginalBaseUrl = originalBaseUrl,
                    AutoGeneratedPost = autoGeneratedPost,
                    AutoGeneratedPostByAI = autoGeneratedPostByAI,
                    IsActive = true,
                    CreatedOn = DateTime.UtcNow,
                    CreatedBy = userId
                };

                await _processedPostRepository.InsertAsync(processedPost, cancellationToken);
            }

            await _uow.CommitAsync();
        }

        public async Task<ProcessedPost?> GetProcessedPostByRepoIdAsync(
            long repoId,
            CancellationToken cancellationToken = default)
        {
            return await _processedPostRepository.SingleOrDefaultAsync(
                p => p.RepoId == repoId && p.IsActive);
        }
    }
}
