using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Published.Core.Entities;

[Table("ProcessedPosts", Schema = "Published")]
public partial class ProcessedPost
{
    [Key]
    public long ProcessedPostId { get; set; }

    public long RepoId { get; set; }

    [StringLength(500)]
    [Unicode(true)]
    public string? Headline { get; set; }

    [StringLength(500)]
    [Unicode(true)]
    public string? OriginalTitle { get; set; }

    [StringLength(500)]
    [Unicode(true)]
    public string? OriginalAuthor { get; set; }

    [Unicode(true)]
    public string? Summary { get; set; }

    [Unicode(true)]
    public string? Takeaways { get; set; }

    [Unicode(true)]
    public string? CTA { get; set; }

    [StringLength(500)]
    [Unicode(true)]
    public string? Hashtags { get; set; }

    [StringLength(500)]
    [Unicode(true)]
    public string? OriginalBaseUrl { get; set; }

    [Unicode(true)]
    public string? AutoGeneratedPost { get; set; }

    [Unicode(true)]
    public string? AutoGeneratedPostByAI { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    public long CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedOn { get; set; }

    public long? UpdatedBy { get; set; }

    [ForeignKey("RepoId")]
    [InverseProperty("ProcessedPosts")]
    public virtual Repo Repo { get; set; } = null!;
}
