using System;
using System.Collections.Generic;
using System.Text;

namespace Home.Application.Response
{
    public class BatchPostResponse
    {
        public long ProcessedPostId { get; set; }

        public long UserId { get; set; }

        public string? Author { get; set; }

        public string? Title { get; set; }

        public string? AutoGeneratedPost { get; set; }

        public string? AutoGeneratedPostByAi { get; set; }

        public string? Source { get; set; }

        public string? RepoUrl { get; set; }

        public DateTime PostedOn { get; set; }
    }
}
