using Home.Application.Commands;
using Home.Core.Entities;
using Home.Core.Persistence;
using MediatR;
using PostIQ.Core.Response;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Home.Application.Handlers
{
    public class CreatePostCommandHandler : IRequestHandler<CreatePostCommand, SingleResponse<long>>
    {
        private readonly HomeDbContext _context;

        public CreatePostCommandHandler(HomeDbContext context)
        {
            _context = context;
        }

        public async Task<SingleResponse<long>> Handle(CreatePostCommand request, CancellationToken cancellationToken)
        {
            var post = new Post
            {
                UserId = request.UserId,
                Author = request.Author ?? "Anonymous",
                AutoGeneratedPost = request.Text,
                AutoGeneratedPostByAi = null,
                Title = null,
                IsActive = true,
                PostedOn = DateTime.UtcNow,
                CreatedOn = DateTime.UtcNow,
                LikeCount = 0,
                CommentCount = 0
            };

            _context.Posts.Add(post);
            await _context.SaveChangesAsync(cancellationToken);

            return new SingleResponse<long>(post.Id);
        }
    }
}
