CREATE TABLE [Home].[Posts](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ProcessedPostId] [bigint] NOT NULL,
	[UserId] [bigint] NOT NULL,
	[Author] [nvarchar](100) NULL,
	[Title] [nvarchar](100) NULL,
	[AutoGeneratedPost] [nvarchar](max) NULL,
	[AutoGeneratedPostByAI] [nvarchar](max) NULL,
	[Source] [varchar](50) NULL,
	[RepoUrl] [varchar](500) NULL,
	[IsActive] [bit] NOT NULL,
	[PostedOn] [datetime] NOT NULL,
	[CreatedOn] [datetime] NULL,
	[CreatedBy] [bigint] NULL,
	[UpdatedOn] [datetime] NULL,
	[UpdatedBy] [bigint] NULL,
 CONSTRAINT [PK_User.Posts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
