CREATE TABLE [Home].[PostLikes](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[PostId] [bigint] NOT NULL,
	[UserId] [bigint] NOT NULL,
	[CreatedOn] [datetime2] NOT NULL,
 CONSTRAINT [PK_PostLikes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [Home].[PostLikes] WITH CHECK ADD CONSTRAINT [FK_PostLikes_Posts_PostId] FOREIGN KEY([PostId])
REFERENCES [Home].[Posts] ([Id])
ON DELETE CASCADE

CREATE NONCLUSTERED INDEX [IX_PostLikes_PostId] ON [Home].[PostLikes]
(
	[PostId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
