CREATE TABLE [Home].[PostsCount](
	[CountId] [bigint] IDENTITY(1,1) NOT NULL,
	[PostId] [bigint] NOT NULL,
	[LikeCount] [int] NOT NULL,
	[CommentCount] [int] NOT NULL,
 CONSTRAINT [PK_Home.PostsCount] PRIMARY KEY CLUSTERED 
(
	[CountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
